--1.Find all properties available for sale within a specific budget range and located in a particular city.

SELECT PropertyID, Availability, ListingType, UnitType, SalePrice, LeasePricePerYear, BuildingYear, DateAdded, Street, City, State, ZipCode, Country
FROM Property p
JOIN Address a ON p.AddressID = a.AddressID
WHERE p.Availability = 'Yes' AND p.SalePrice BETWEEN 300000 AND 600000 AND a.City = 'New York';

--2.List all appointments made for a specific client along with the details of the property and the agent.

SELECT ap.AppointmentID, p.PropertyID, p.unittype, p.listingtype, e.FirstName AS AgentFirstName, e.LastName AS AgentLastName, ap.AppointmentMadeDate, ap.VisitDate
FROM Appointment ap
JOIN Client c ON ap.ClientID = c.ClientID
JOIN Property p ON ap.PropertyID = p.PropertyID
JOIN Employee e ON ap.AgentID = e.EmployeeID
WHERE c.ClientID = 3;

--3. Calculate the total commission generated by each agent from completed transactions.

SELECT e.EmployeeID, e.FirstName, e.LastName, SUM(c.Amount)*0.1 AS TotalCommission
FROM Employee e
JOIN Transaction t ON e.EmployeeID = t.AgentID
JOIN Contract c ON t.TransactionID = c.TransactionID
GROUP BY e.EmployeeID, e.FirstName, e.LastName;

--4. List all feedback provided by clients for a specific agent along with their ratings.

SELECT f.FeedbackID, c.FirstName AS ClientFirstName, c.LastName AS ClientLastName, f.Rating, f.Feedback, f.InteractionType, f.FeedbackDate
FROM Feedback f
JOIN Client c ON f.ClientID = c.ClientID
WHERE f.AgentID = 14;

--5. Retrieve all properties along with their owners' contact details.

SELECT p.PropertyID, p.Availability, p.ListingType, p.UnitType, p.SalePrice, p.LeasePricePerYear, p.BuildingYear, o.FirstName, o.LastName, o.Phone, o.Email
FROM Property p
JOIN Owns ow ON p.PropertyID = ow.PropertyID
JOIN Owner o ON ow.OwnerID = o.OwnerID;

--6. Generate a list of all clients who have a budget above a specific amount and are looking for a specific type of property.

SELECT c.ClientID, c.FirstName, c.LastName, cpp.PreferredPropertyType, cpp.Budget
FROM Client c
JOIN ClientPropertyPreferences cpp ON c.ClientID = cpp.ClientID
WHERE c.DesiredTransactionType = 'Rent'AND cpp.Budget > 20000 AND cpp.PreferredPropertyType = '3B2B';

--7. Find all costs incurred in a specific office in a specific month along with their descriptions.

SELECT ci.CostItem, c.CostDescription, c.Amount, c.Time
FROM Cost c
JOIN CostItem ci ON c.CostItemID = ci.CostItemID
WHERE DATE_TRUNC('month', c.Time) = DATE_TRUNC('month', CURRENT_DATE - INTERVAL '14 month') AND c.OfficeID = 1;

--8. Find all by our clients (Some properties are rented by outside clients so we do not have their information)along with the details of the tenants.

SELECT p.PropertyID, p.ListingType, p.UnitType, p.LeasePricePerYear, c.FirstName AS ClientFirstName, c.LastName AS ClientLastName, c.Phone, c.Email
FROM Property p
JOIN Contract con ON p.PropertyID = con.PropertyID
JOIN Client c ON con.ClientID = c.ClientID
WHERE p.Availability = 'No' and p.listingtype = 'Rent';

--9. Retrieve all contracts along with the agents, clients, and properties involved, including the start and end dates of the contracts.

SELECT con.ContractID, con.StartDate, con.EndDate, e.FirstName AS AgentFirstName, e.LastName AS AgentLastName, c.FirstName AS ClientFirstName, c.LastName AS ClientLastName, p.PropertyID
FROM Contract con
JOIN Transaction t ON con.TransactionID = t.TransactionID
JOIN Employee e ON t.AgentID = e.EmployeeID
JOIN Client c ON con.ClientID = c.ClientID
JOIN Property p ON con.PropertyID = p.PropertyID;

--Advanced:
--10.Find the top 5 agents based on the number of transactions they’ve completed in the last year and the total revenue generated from those transactions.

SELECT e.EmployeeID, e.FirstName, e.LastName, COUNT(t.TransactionID) AS TransactionCount, SUM(c.Amount) AS TotalRevenue
FROM Employee e
JOIN Transaction t ON e.EmployeeID = t.AgentID
JOIN Contract c ON t.TransactionID = c.TransactionID
WHERE t.TransactionDate >= CURRENT_DATE - INTERVAL '1 year'
GROUP BY e.EmployeeID, e.FirstName, e.LastName
ORDER BY TotalRevenue DESC
LIMIT 5;

--11. List properties that have not been viewed by any clients in the past six months.

SELECT p.PropertyID, p.ListingType, p.UnitType, p.SalePrice, p.LeasePricePerYear, p.BuildingYear, p.DateAdded
FROM Property p
LEFT JOIN Appointment a ON p.PropertyID = a.PropertyID AND a.VisitDate >= CURRENT_DATE - INTERVAL '6 months'
WHERE a.AppointmentID IS NULL;

--12. Calculating the total number of properties owned by each owner, segmented by property type.

SELECT o.OwnerID, o.FirstName, o.LastName, 
       COUNT(CASE WHEN p.UnitType = '3B2B' THEN 1 END) AS AptCount,
       COUNT(CASE WHEN p.UnitType = 'condo' THEN 1 END) AS condoCount,
       COUNT(CASE WHEN p.UnitType = 'studio' THEN 1 END) AS studioCount
FROM Owner o
JOIN Owns ow ON o.OwnerID = ow.OwnerID
JOIN Property p ON ow.PropertyID = p.PropertyID
GROUP BY o.OwnerID, o.FirstName, o.LastName;
